Repository AY2021S1-CS2103-T16-1/tp, pull requests merged in 2020-11, with the labels that each got.

#196 Add images for menu
  src/main/java/seedu/address/model/food/MenuItem.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/FoodCard.java
  src/main/resources/images/food/butter_chicken.png
  src/main/resources/images/food/cheese_fries.png
  src/main/resources/images/food/kampong.png
  src/main/resources/images/food/milo.png
  src/main/resources/images/food/milo_dino.png
  src/main/resources/images/food/milo_god.png
  src/main/resources/images/food/pattaya.png
  src/main/resources/images/food/roti_john.png
  src/main/resources/images/food/sambal_chicken.png
  src/main/resources/images/food/teh_ping.png
  src/main/resources/images/food/veg_briyani.png
Labels: enhancement

#197 Fix bug with menu image
  src/main/resources/images/food/milo_god.png
  src/main/resources/images/food/sambal_chicken.png
  src/main/resources/view/FoodListCard.fxml
Labels: bug

#202 Fix profile command and submit test cases
  .gitignore
  docs/UserGuide.md
  src/data/JsonProfileStorageTest/TypicalProfile.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ProfileCommand.java
  src/main/java/seedu/address/logic/commands/SubmitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ProfileCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/profile/Profile.java
  src/main/java/seedu/address/storage/JsonAdaptedProfile.java
  src/main/java/seedu/address/storage/JsonProfileManagerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableProfileManager.java
  src/main/java/seedu/address/storage/PresetManagerStorage.java
  src/main/java/seedu/address/storage/ProfileManagerStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonProfileStorageTest/TypicalProfile.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SubmitCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement

#205 Add images for DeFrank and add default image
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/FoodCard.java
  src/main/resources/images/food/al_amaan/butter_chicken.png
  src/main/resources/images/food/al_amaan/cheese_fries.png
  src/main/resources/images/food/al_amaan/kampong.png
  src/main/resources/images/food/al_amaan/milo.png
  src/main/resources/images/food/al_amaan/milo_dino.png
  src/main/resources/images/food/al_amaan/milo_god.png
  src/main/resources/images/food/al_amaan/pattaya.png
  src/main/resources/images/food/al_amaan/roti_john.png
  src/main/resources/images/food/al_amaan/sambal_chicken.png
  src/main/resources/images/food/al_amaan/teh_ping.png
  src/main/resources/images/food/al_amaan/veg_briyani.png
  src/main/resources/images/food/de_frank/bacon_cheese_hotdog.png
  src/main/resources/images/food/de_frank/cheese_steak_slider.png
  src/main/resources/images/food/de_frank/chicken_burger.png
  src/main/resources/images/food/de_frank/corn_dog.png
  src/main/resources/images/food/de_frank/fish_burger.png
  src/main/resources/images/food/de_frank/foie_grass.png
  src/main/resources/images/food/de_frank/ribeye_burger.png
  src/main/resources/images/food/de_frank/sauerkraut_hotdog.png
  src/main/resources/images/food/default-menu-item.jpg
  src/main/resources/images/food/makan_xpress/meatball_spagetti.png
  src/main/resources/images/food/makan_xpress/naan.png
  src/main/resources/images/food/makan_xpress/nasi_goreng.png
  src/main/resources/images/food/makan_xpress/pattaya.png
  src/main/resources/images/food/makan_xpress/prata.png
  src/main/resources/images/food/makan_xpress/tandoori.png
  src/main/resources/images/food/makan_xpress/tomyam.png
  src/test/data/JsonSerializablePresetManagerTest/savePreset.json
Labels: enhancement

#211 Change GitHub username to lowercase for PPP
  docs/team/kendrewchan.md
Labels: documentation

#223 Update tag and untag in DG and make PPP
  docs/DeveloperGuide.md
  docs/diagrams/TagCommandActivityDiagram.puml
  docs/diagrams/UntagCommandActivityDiagram.puml
  docs/images/TagCommandActivityDiagram.png
  docs/images/UntagCommandActivityDiagram.png
  docs/team/ebolaeater.md
Labels: documentation

#225 Add Load and Save Presets for DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LoadPresetSequenceDiagram.puml
  docs/diagrams/SavePresetSequenceDiagram.puml
  docs/images/LoadPresetCommandSequenceDiagram.png
  docs/images/SavePresetCommandSequenceDiagram.png
Labels: documentation

#226 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/LoadPresetCommandActivityDiagram.puml
  docs/diagrams/SavePresetCommandActivityDiagram.puml
  docs/images/LoadPresetCommandActivityDiagram.png
  docs/images/SavePresetCommandActivityDiagram.png
Labels: documentation

#227 Update README
  README.md
  docs/images/UI.png
  docs/images/Ui.png
  src/test/data/JsonSerializablePresetManagerTest/savePreset.json
Labels: documentation

#230 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/TotalCommand.java
  src/main/java/seedu/address/logic/parser/PresetCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/vendor/VendorManager.java
  src/test/data/JsonSerializablePresetManagerTest/savePreset.json
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/PresetCommandParserTest.java
Labels: documentation
