Repository AY2021S1-CS2103-T16-1/tp, pull requests merged in 2020-10, with the labels that each got.

#70 Add MenuManagerStorage and tests
  menu/menu1.json
  src/main/java/seedu/address/storage/JsonAdaptedFood.java
  src/main/java/seedu/address/storage/JsonMenuManagerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableMenuManager.java
  src/main/java/seedu/address/storage/MenuManagerStorage.java
  src/test/data/JsonSerializableMenuManagerTest/duplicateFoods.json
  src/test/data/JsonSerializableMenuManagerTest/invalidMenuManager.json
  src/test/data/JsonSerializableMenuManagerTest/typicalMenuManager.json
  src/test/java/seedu/address/storage/JsonAdaptedFoodTest.java
  src/test/java/seedu/address/storage/JsonSerializableMenuManagerTest.java
Labels: enhancement

#86 Fix VendorCommand and Menu
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/VendorCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/VendorCommandTest.java
Labels: bug, enhancement

#92 Improve vendor part of DG
  docs/DeveloperGuide.md
Labels: documentation

#94 Update Developer guide
  docs/DeveloperGuide.md
  docs/images/ArchitectureSequenceDiagram.png
Labels: documentation

#95 Add sequence diagram for Vendor Command
  docs/DeveloperGuide.md
  docs/images/VendorCommandSequenceDiagram.png
Labels: documentation

#109 Update VendorCommand in DG
  docs/DeveloperGuide.md
Labels: documentation

#110 Developer Guide Update: OrderCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddCommand.xml
  docs/images/AddCommandDiagram.png
  docs/images/ClearCommandDiagram.png
  docs/images/RemoveCommandDiagram.png
Labels: documentation

#111 Update DG undo
  docs/DeveloperGuide.md
Labels: documentation

#137 Update userguide
  docs/UserGuide.md
Labels: documentation

#186 Update UserGuide
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: documentation
